// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/workshop-example": {
    params: {};
  };
  "/fitness-example": {
    params: {};
  };
  "/beauty-example": {
    params: {};
  };
  "/course-example": {
    params: {};
  };
  "/food-example": {
    params: {};
  };
  "/sitemap.xml": {
    params: {};
  };
  "/robots.txt": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/workshop-example" | "/fitness-example" | "/beauty-example" | "/course-example" | "/food-example" | "/sitemap.xml" | "/robots.txt" | "/*";
  };
  "routes/[workshop-example]._index.tsx": {
    id: "routes/[workshop-example]._index";
    page: "/workshop-example";
  };
  "routes/[fitness-example]._index.tsx": {
    id: "routes/[fitness-example]._index";
    page: "/fitness-example";
  };
  "routes/[beauty-example]._index.tsx": {
    id: "routes/[beauty-example]._index";
    page: "/beauty-example";
  };
  "routes/[course-example]._index.tsx": {
    id: "routes/[course-example]._index";
    page: "/course-example";
  };
  "routes/[food-example]._index.tsx": {
    id: "routes/[food-example]._index";
    page: "/food-example";
  };
  "routes/[sitemap.xml]._index.tsx": {
    id: "routes/[sitemap.xml]._index";
    page: "/sitemap.xml";
  };
  "routes/[robots.txt].tsx": {
    id: "routes/[robots.txt]";
    page: "/robots.txt";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/$.tsx": {
    id: "routes/$";
    page: "/*";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/[workshop-example]._index": typeof import("./app/routes/[workshop-example]._index.tsx");
  "routes/[fitness-example]._index": typeof import("./app/routes/[fitness-example]._index.tsx");
  "routes/[beauty-example]._index": typeof import("./app/routes/[beauty-example]._index.tsx");
  "routes/[course-example]._index": typeof import("./app/routes/[course-example]._index.tsx");
  "routes/[food-example]._index": typeof import("./app/routes/[food-example]._index.tsx");
  "routes/[sitemap.xml]._index": typeof import("./app/routes/[sitemap.xml]._index.tsx");
  "routes/[robots.txt]": typeof import("./app/routes/[robots.txt].tsx");
  "routes/_index": typeof import("./app/routes/_index.tsx");
  "routes/$": typeof import("./app/routes/$.tsx");
};